openapi: 3.0.3
info:
  title: Account Opening, Management and Money Transfer API
  version: 1.0.0
  description: API for opening and managing accounts and performing money transfers.
servers:
  - url: /api/v1
paths:
  /accounts:
    post:
      summary: Open a new account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: string
                accountType:
                  $ref: '#/components/schemas/AccountType'
                currency:
                  $ref: '#/components/schemas/CurrencyCode'
      responses:
        '201':
          description: Account created
    get:
      summary: List all accounts
      responses:
        '200':
          description: A list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'

  /accounts/{accountId}:
    get:
      summary: Get account details
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Account details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'

  /accounts/transfer:
    post:
      summary: Transfer money between accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                to:
                  type: string
                amount:
                  type: number
                currency:
                  $ref: '#/components/schemas/CurrencyCode'
      responses:
        '200':
          description: Transfer successful

  /accounts/{accountId}/close:
    post:
      summary: Close an account
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Account closed successfully
        '404':
          description: Account not found
components:
  schemas:
    Account:
      type: object
      properties:
        accountId:
          type: string
        customerId:
          type: string
        accountType:
          $ref: '#/components/schemas/AccountType'
        balance:
          type: number
        currency:
          $ref: '#/components/schemas/CurrencyCode'
        createdAt:
          type: string
          format: date-time
    AccountType:
      type: string
      enum: [SAVINGS, CHECKING, BUSINESS, JOINT]
    CurrencyCode:
      type: string
      pattern: '^[A-Z]{3}$'
      description: ISO 4217 currency code (e.g., USD, EUR)
