openapi: 3.0.3
info:
  title: Card Management API
  version: 1.0.0
  description: API for managing debit and credit cards.
servers:
  - url: /api/v1
paths:
  /cards:
    post:
      summary: Request a new card
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: string
                cardType:
                  $ref: '#/components/schemas/CardType'
                cardProvider:
                  $ref: '#/components/schemas/CardProvider'
      responses:
        '201':
          description: Card requested
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
        '400':
          description: Invalid request body or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Card request conflict (e.g., duplicate request)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: List all cards for a customer
      parameters:
        - name: customerId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of cards
        '400':
          description: Invalid customer ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /cards/{cardNumber}/status:
    patch:
      summary: Update card status (activate, deactivate, report lost/stolen, etc.)
      parameters:
        - name: cardNumber
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  $ref: '#/components/schemas/CardStatus'
      responses:
        '200':
          description: Card status updated
        '400':
          description: Invalid card number or status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Card not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Status change conflict (e.g., already in requested state)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /cards/{cardNumber}:
    get:
      summary: Get card details by card number
      parameters:
        - name: cardNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Card details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
        '404':
          description: Card not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Card:
      type: object
      properties:
        cardNumber:
          type: string
          description: Card number
        customerId:
          type: string
        cardType:
          $ref: '#/components/schemas/CardType'
        cardProvider:
          $ref: '#/components/schemas/CardProvider'
        cvv:
          type: string
          description: Card verification value (masked or omitted in production)
        expiry:
          type: string
          description: Expiry date in MM/YY format
        status:
          $ref: '#/components/schemas/CardStatus'
        issuedAt:
          type: string
          format: date-time
          description: Card issue date
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Error code identifier
        message:
          type: string
          description: Human-readable error message
        details:
          type: string
          description: Additional error details (optional)
    CardStatus:
      type: string
      enum: [ ACTIVE, INACTIVE, BLOCKED, EXPIRED, LOST, STOLEN ]
    CardType:
      type: string
      enum:
        - debit
        - credit
    CardProvider:
      type: string
      enum:
        - visa
        - mastercard
        - maestro
        - amex
        - discover
