openapi: 3.0.3
info:
  title: Foreign Exchange (FX) Services API
  version: 1.0.0
  description: API to provide foreign exchange rate and conversion services.
servers:
  - url: /api/v1
paths:
  /fx/rates:
    get:
      summary: Get FX rates
      parameters:
        - name: baseCurrency
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: FX rates returned
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Base currency not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /fx/convert:
    post:
      summary: Convert currency
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fromCurrency:
                  type: string
                toCurrency:
                  type: string
                amount:
                  type: number
      responses:
        '200':
          description: Conversion result
        '400':
          description: Invalid request body or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Currency not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conversion conflict (e.g., unsupported currency pair)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Error code identifier
        message:
          type: string
          description: Human-readable error message
        details:
          type: string
          description: Additional error details (optional)
