openapi: 3.0.3
info:
  title: Transaction History API
  version: 1.0.0
  description: API to retrieve account transaction histories.
servers:
  - url: /api/v1
paths:
  /transactions:
    get:
      summary: Get transactions for an account
      parameters:
        - name: accountId
          in: query
          required: true
          schema:
            type: string
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of transactions
