openapi: 3.0.3
info:
  title: Transaction History API
  version: 1.0.0
  description: API to retrieve account transaction histories.
servers:
  - url: /api/v1
paths:
  /transactions:
    get:
      summary: Get transactions for an account
      parameters:
        - name: accountId
          in: query
          required: true
          schema:
            type: string
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Transaction retrieval conflict (e.g., date range too large)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Transaction:
      type: object
      properties:
        transactionId:
          type: string
        accountId:
          type: string
        type:
          type: string
          enum: [DEPOSIT, WITHDRAWAL, TRANSFER, PAYMENT, FEE, INTEREST, ADJUSTMENT]
        amount:
          type: number
        currency:
          type: string
          pattern: '^[A-Z]{3}$'
          description: ISO 4217 currency code (e.g., USD, EUR)
        description:
          type: string
        status:
          type: string
          enum: [PENDING, COMPLETED, FAILED, REVERSED]
        timestamp:
          type: string
          format: date-time
        relatedAccountId:
          type: string
          description: Account ID involved in transfer/payment (if applicable)
        reference:
          type: string
          description: External or internal reference for the transaction
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Error code identifier
        message:
          type: string
          description: Human-readable error message
        details:
          type: string
          description: Additional error details (optional)
